version: '3'
services:
  vm:
    build: .
    ports:
    - "4000:80"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
  mongo:
    image: mongo
  redis:
    image: redis
  cassandra:
    image: cassandra
  neo:
    image: neo4j:3.0
